# Generated by Django 3.1.1 on 2020-10-13 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201013_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Thumnail',
            new_name='thumbnail',
        ),
    ]
