# Generated by Django 3.1.1 on 2020-10-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201013_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='picture',
        ),
    ]
