# Generated by Django 3.1.1 on 2020-10-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201013_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='thumbnail',
        ),
    ]
