# Generated by Django 3.0.5 on 2020-11-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_postth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
