# Generated by Django 3.0.5 on 2020-11-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_imagespost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagespost',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagespost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
