# Generated by Django 3.0.5 on 2020-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20201109_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagespost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='base.Tag'),
        ),
    ]
