# Generated by Django 3.0.5 on 2020-11-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_imagespost_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTH',
            new_name='Postimg',
        ),
        migrations.DeleteModel(
            name='ImagesPost',
        ),
    ]
