# Generated by Django 3.0.5 on 2020-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20201109_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimg',
            name='picture1',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='postimg',
            name='picture2',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='postimg',
            name='picture3',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='postimg',
            name='picture4',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='postimg',
            name='picture5',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='postimg',
            name='picture6',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
    ]
