# Generated by Django 3.0.5 on 2020-11-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20201110_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimg',
            name='picture7',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='postimg',
            name='picture8',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
    ]
