# Generated by Django 3.0.5 on 2020-11-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20201110_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimg',
            name='picture',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture1',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture2',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture3',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture4',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture5',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture6',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture7',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
        migrations.AlterField(
            model_name='postimg',
            name='picture8',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='gallerys'),
        ),
    ]
