# Generated by Django 3.0.5 on 2020-11-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_postcomment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
